---
title: "Jefferson Cup Week 3 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggthemes)
library(plotly)
library(DT)
library(stringr)
library(glue)
source("../R/fetch_powerrankings.R")
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

Row
-----------------------------------------------------------------------

### Power Rankings

```{r}
pr_week3 <- get_powerrankings(2017, 3, data_dir = "../data")
```

Row
-----------------------------------------------------------------------

### Trends

```{r}
trends_df <- read_trends(2017)
p <- trends_df %>% 
  filter(trend_type == "power_rank",
         !is.na(rank)) %>% 
  mutate(week = forcats::fct_inorder(week)) %>% 
  ggplot(aes(x = as.numeric(week), y = rank)) +
  geom_line(aes(colour = Team)) +
  scale_colour_viridis_d() +
  scale_x_continuous(breaks = c(1, 2, 3, 4),
                     labels = c("0", "1", "2", "3")) +
  scale_y_reverse(breaks = 1:12)
ggplotly(p)
```

### Chart C

```{r}

```

