---
title: "Jefferson Cup 2017 — Week 12 Jogboard"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(stringr)
library(ggplot2)
library(ggthemes)
library(plotly)
library(networkD3)
library(htmlwidgets)
library(DT)
library(stringr)
library(glue)
source("../R/fetch_powerrankings.R")
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)

custom_theme_bw <- function() {
    theme_bw() +
        theme(axis.title = element_text(face = "bold"),
              legend.title = element_text(face = "bold"),
              plot.title = element_text(face = "bold"))
}
```


Rivalry Review
=====================================  

## **Breakdowns & Predictions**

```{r, message=FALSE, warning=FALSE}
brad_v_drew <- tibble(Matchup = "Brad (10-3)</br>vs.</br>Drew (7-5)",
                      `ESPN Projections` = "<b>99.6</b></br>to</br>87",
                      `FantasyPros Projections` = "<b>101</b></br>to</br>94",
                      Notes = glue("Brad and Drew have both displayed a confusing mix of tite and not at all tite performances this year. Brad has obviously executed this strategy with greater success, but Drew is very much still in it. I'm not really sure who's on Drew's team anymore besides Carson Wentz, but that seems to be good enough. As much as I want to see a rematch in the 1-4 seed matchup next week, I'm predicting that Brad rides Orleans “the Dark Horse” Darkwa to victory and a shot to tie Drew's overall season wins record.


<b>Rivalry impact rating: 6.0</b> I'm sure eliminating Drew from the playoffs would make Brad extremely happy, but it just doesn't have the same bite as sentencing one's rival to a painful trial of human endurance. Drew beating Brad, on the other hand, would just be a teaser for Week 14. I expect the trash talk will be entertaining though."))

james_v_tony <- tibble(Matchup = "James (7-5)</br>vs.</br>Tony (4-9)",
                       `ESPN Projections` = "<b>97.1</b></br>to</br>93.2",
                       `FantasyPros Projections` = "<b>103</b></br>to</br>92.4",
                       Notes = glue("Fatherhood has apparently sent Tony's once respectable fantasy prowess into a downward spiral that will hopefully lead to years of mediocrity. Still, he has a knack for beating me when it counts the most. Attempting to cap off the greatest comeback in recent memory — from 1-5 to 8-5 and a playoff berth — I just need to get past a resurgent Julio Jones and his complementing cast of.. whatever. With most of my team lighting it up over the past few weeks, I think it can be done. 


<b>Rivalry impact rating: 7.8 —</b> Clinching a playoff spot after my disastrous start to the season and sealing Tony's last place finish in the process would be tiiiite. Unfortunately, Tony would need some help from Keith and Billy to get his jog on. Still, there's a lot of potential for one of us to make the other very sad."))

toby_v_shep <- tibble(Matchup = "Toby (6-6)</br>vs.</br>Shep (7-5)",
                      `ESPN Projections` = "82.6</br>to</br><b>91.1</b>",
                      `FantasyPros Projections` = "87</br>to</br><b>95</b>",
                      Notes = glue("Toby had some legit potential coming into the season, but the loss of Dalvin Cook (and more recently Foreman), combined with some poor management and the decline of the Chiefs, has left him firmly situated to finish in the middle of the pack. Shep was able to use Zeke perhaps more than anyone expected this year, but his stable of 18 RB2 types (and/or his management thereof) has disappointed since the suspension took effect.


<b>Rivalry impact rating: 4.6 —</b> This is pretty one sided: Shep could really use a win to secure a playoff spot, while Toby will probably finish around 6th either way. Spoiler potential is always fun though. Go Tobes!"))

billy_v_matt <- tibble(Matchup = "Billy (3-9)</br>vs.</br>Matt (6-6)",
                       `ESPN Projections` = "85.5</br>to</br><b>95.7</b>",
                       `FantasyPros Projections` = "90</br>to</br><b>100</b>",
                       Notes = glue("Matt seems to have mastered the art of a strong start followed by a slow and painful collapse. Billy, meanwhile, is more famous for his annual mediocre start followed by a slow and painful collapse. They both have a lot to play for this week: Matt needs a win to make the playoffs, and Billy is the odds-on favorite to run a marathon. On paper, this could be anyone's game, but history suggests that Matt will find a way to win. I side with history — and math — to give the nod to Matt. 


<b>Rivalry impact rating: 9.2 —</b> Oh, how the tables have turned... Two years ago, this game was about avoiding open mic standup. Now, Billy and Matt have the opportunity to determine each other's <i>very different</i> fates. Given the broader consequences of this matchup on both the playoff and LPP results, this one calls for some popcorn."))

milf_v_ross <- tibble(Matchup = "Milf (6-6)</br>vs.</br>Ross (4-9)",
                      `ESPN Projections` = "<b>91.4</b></br>to</br>86.7",
                      `FantasyPros Projections` = "<b>93.9</b></br>to</br>91.9",
                      Notes = glue("I feel like this rivalry is embodied by contrasting examples of how life can get in the way of fantasy football. Ross, unlike the other rookies in the league, is in full on dad mode; Milf is pretty much the opposite. In both cases, these distractions might explain why Ross and Milf have eached looked awesome at times this season, then completely terrible other weeks. While all of Ross' Panthers have been solid lately, my money is on Gurley and Team Milf this week.


<b>Rivalry impact rating: 3.3 —</b> These sneaky good / sneaky bad Virginia Tech alums are facing off for a miracle shot at the playoffs OR an outside chance at finishing last. While the outcomes are enticing, the small odds of either happening make this matchup a bit of a snoozer (apnea free, courtesy of Milf's CPAP machine)."))

keith_v_kevin <- tibble(Matchup = "Keith (3-9)</br>vs.</br>Kevin (9-3)",
                        `ESPN Projections` = "92.4</br>to</br><b>97.2</b>",
                        `FantasyPros Projections` = "94</br>to</br>94",               
                        Notes = "Kevin has taken advantage of an elite defense to claim the Coastal Division title, but a few of his premier players have been disappointing down the stretch. Keith has employed a unique blend of incompetence and indifference to end up in a virtual tie for last place, but now has Antonio Brown and managed to evade a chafed nipple fate last week. Still, I expect Kevin's guys to bounce back — and Big Ben effectively neutralizes AB (some) — leaving Keith to pray that Billy doesn't overcome the point deficit. Matt and Kevin have a much better chance to cause great suffering for their rivals, sadly letting Tony off the hook.


<b>Rivalry impact rating: 8.1 —</b> If Kevin hadn't already clinched a playoff spot, this matchup might have been the winner — way to go, dick. As it is, the distinct possibility of a 1st-vs.-last rivalry is pretty delicious. On the other hand, the best possible outcome of Keith winning is that Keith is really excited, and nobody wants that.")

rivalry_df <- bind_rows(brad_v_drew, james_v_tony, toby_v_shep, 
                           billy_v_matt, milf_v_ross, keith_v_kevin) %>% 
  mutate(Notes = str_replace(Notes, "\n", "<br/><br/>"),
         Matchup = str_c("<b>", Matchup, "</b>"))
```


```{r}
rivalry_df %>%
  datatable(escape = FALSE, rownames = FALSE, height = 2800,
            options=list(
              scrollY = TRUE,
              ordering = FALSE,
              pageLength = 12,
              dom = 't',
              initComplete = JS("
                                function(settings, json) {
                                  $(this.api().table().body()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                  $(this.api().table().header()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '13px'
                                  });
                                  $(this.api().table().container()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '13px'
                                  });
                                }
                                ")
            )
  ) %>% 
  formatStyle(c("Matchup", "ESPN Projections"), textAlign = "center")
```

Playoff Scenarios
=====================================  

Row 
-----------------------------------------------------------------------

### **Paths to Glory**

```{r include=FALSE, message=FALSE, warning=FALSE}
links = tribble(
  ~source, ~target, ~value, ~owner, ~scenario,
  0, 24, 0.2, "James", "J1",
  11, 24, 0.2, "James", "J1",
  0, 25, 0.2, "James", "J2",
  13, 25, 0.2, "James", "J2",
  0, 26, 0.2, "James", "J3",
  3, 26, 0.2, "James", "J3",
  0, 27, 0.2, "James", "J4",
  5, 27, 0.2, "James", "J4",
  1, 28, 0.2, "James", "J5",
  3, 28, 0.2, "James", "J5",
  11, 28, 0.2, "James", "J5",
  5, 28, 0.2, "James", "J5",
  13, 28, 0.2, "James", "J5",
  1, 29, 0.2, "James", "J6",
  7, 29, 0.2, "James", "J6",
  3, 29, 0.2, "James", "J6",
  11, 29, 0.2, "James", "J6",
  1, 30, 0.2, "James", "J7",
  7, 30, 0.2, "James", "J7",
  5, 30, 0.2, "James", "J7",
  13, 30, 0.2, "James", "J7",
  2, 31, 0.2, "Drew", "D1",
  10, 31, 0.2, "Drew", "D1",
  2, 32, 0.2, "Drew", "D2",
  15, 32, 0.2, "Drew", "D2",
  2, 33, 0.2, "Drew", "D3",
  1, 33, 0.2, "Drew", "D3",
  2, 34, 0.2, "Drew", "D4",
  5, 34, 0.2, "Drew", "D4",
  3, 35, 0.2, "Drew", "D5",
  1, 35, 0.2, "Drew", "D5",
  10, 35, 0.2, "Drew", "D5",
  5, 35, 0.2, "Drew", "D5",
  15, 35, 0.2, "Drew", "D5",
  19, 35, 0.2, "Drew", "D5",
  3, 36, 0.2, "Drew", "D6",
  7, 36, 0.2, "Drew", "D6",
  1, 36, 0.2, "Drew", "D6",
  10, 36, 0.2, "Drew", "D6",
  19, 36, 0.2, "Drew", "D6",
  3, 37, 0.2, "Drew", "D7",
  7, 37, 0.2, "Drew", "D7",
  5, 37, 0.2, "Drew", "D7",
  15, 37, 0.2, "Drew", "D7",
  19, 37, 0.2, "Drew", "D7",
  23, 37, 0.2, "Drew", "D7",
  4, 38, 0.2, "Shep", "S1",
  12, 38, 0.2, "Shep", "S1",
  4, 39, 0.2, "Shep", "S2",
  14, 39, 0.2, "Shep", "S2",
  4, 40, 0.2, "Shep", "S3",
  1, 40, 0.2, "Shep", "S3",
  4, 41, 0.2, "Shep", "S4",
  3, 41, 0.2, "Shep", "S4",
  5, 42, 0.2, "Shep", "S5",
  7, 42, 0.2, "Shep", "S5",
  3, 42, 0.2, "Shep", "S5",
  14, 42, 0.2, "Shep", "S5",
  17, 42, 0.2, "Shep", "S5",
  21, 42, 0.2, "Shep", "S5",
  6, 43, 0.2, "Matt", "M1",
  1, 43, 0.2, "Matt", "M1",
  3, 43, 0.2, "Matt", "M1",
  6, 44, 0.2, "Matt", "M2",
  1, 44, 0.2, "Matt", "M2",
  5, 44, 0.2, "Matt", "M2",
  6, 45, 0.2, "Matt", "M3",
  3, 45, 0.2, "Matt", "M3",
  5, 45, 0.2, "Matt", "M3",
  8, 46, 0.2, "Milf", "W1",
  7, 46, 0.2, "Milf", "W1",
  3, 46, 0.2, "Milf", "W1",
  18, 46, 0.2, "Milf", "W1",
  5, 46, 0.2, "Milf", "W1",
  20, 46, 0.2, "Milf", "W1",
  48, 46, 0.2, "Milf", "W1",
  5, 49, 0.2, "Toby", "T1",
  16, 49, 0.2, "Toby", "T1",
  7, 49, 0.2, "Toby", "T1",
  3, 49, 0.2, "Toby", "T1",
  22, 49, 0.2, "Toby", "T1",
  47, 49, 0.2, "Toby", "T1",
  5, 50, 0.2, "Toby", "T2",
  16, 50, 0.2, "Toby", "T2",
  7, 50, 0.2, "Toby", "T2",
  3, 50, 0.2, "Toby", "T2",
  22, 50, 0.2, "Toby", "T2",
  9, 50, 0.2, "Toby", "T2",
  24, 51, 0.4, "James", "",
  25, 51, 0.4, "James", "",    
  26, 51, 0.4, "James", "",
  27, 51, 0.4, "James", "",
  28, 51, 1, "James", "",
  29, 51, 0.8, "James", "",
  30, 51, 0.8, "James", "",
  31, 52, 0.4, "Drew", "",
  32, 52, 0.4, "Drew", "",    
  33, 52, 0.4, "Drew", "",
  34, 52, 0.4, "Drew", "",
  35, 52, 1.2, "Drew", "",
  36, 52, 1, "Drew", "",
  37, 52, 1.2, "Drew", "",
  38, 53, 0.4, "Shep", "",
  39, 53, 0.4, "Shep", "",    
  40, 53, 0.4, "Shep", "",
  41, 53, 0.4, "Shep", "",
  42, 53, 1.2, "Shep", "",
  43, 54, 0.6, "Matt", "",
  44, 54, 0.6, "Matt", "",
  45, 54, 0.6, "Matt", "",
  46, 55, 1.4, "Milf", "",    
  49, 56, 1.2, "Toby", "",
  50, 56, 1.2, "Toby", ""
)

nodes = tribble(
  ~node, ~name, ~foo,
  0, "James beats Tony", "R",
  1, "Tony beats James", "R",
  2, "Drew beats Brad", "R",
  3, "Brad beats Drew", "R",
  4, "Shep beats Toby", "R",
  5, "Toby beats Shep", "R",
  6, "Matt beats Billy", "R",
  7, "Billy beats Matt", "R",
  8, "Milf beats Ross", "R",
  9, "Ross beats Milf", "R",
  10, "Drew scores > James + 54.4", "Points",
  11, "Drew scores < James + 54.4", "Points",
  12, "Shep scores > James + 78.1", "Points",
  13, "Shep scores < James + 78.1", "Points",
  14, "Shep scores > Drew + 23.7", "Points",
  15, "Shep scores < Drew + 23.7", "Points",
  16, "Toby scores > Shep + 75.1", "Points",
  17, "Toby scores < Shep + 75.1", "Points",
  18, "Milf scores > Drew + 64.8", "Points",
  19, "Milf scores < Drew + 64.8", "Points",
  20, "Milf scores > Shep + 41.1", "Points",
  21, "Milf scores < Shep + 41.1", "Points",
  22, "Toby scores > Drew + 98.8", "Points",
  23, "Toby scores < Drew + 98.8", "Points",
  24, "J1", "James",
  25, "J2", "James",
  26, "J3", "James",
  27, "J4", "James",
  28, "J5", "James",
  29, "J6", "James",
  30, "J7", "James",
  31, "D1", "Drew",
  32, "D2", "Drew",
  33, "D3", "Drew",
  34, "D4", "Drew",
  35, "D5", "Drew",
  36, "D6", "Drew",
  37, "D7", "Drew",
  38, "S1", "Shep",
  39, "S2", "Shep",
  40, "S3", "Shep",
  41, "S4", "Shep",
  42, "S5", "Shep",
  43, "M1", "Matt",
  44, "M2", "Matt",
  45, "M3", "Matt",
  46, "W1", "Milf",
  47, "Toby scores > Milf + 34", "Points",
  48, "Toby scores < Milf + 34", "Points",
  49, "T1", "Toby",
  50, "T2", "Toby",
  51, "James PLAYOFFS", "James",
  52, "Drew PLAYOFFS", "Drew",
  53, "Shep PLAYOFFS", "Shep",
  54, "Matt PLAYOFFS", "Matt",
  55, "Milf PLAYOFFS", "Milf",
  56, "Toby PLAYOFFS", "Toby"
)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
sn <- sankeyNetwork(
  Links = links,
  Nodes = nodes, 
  Source = "source",
  Target = "target", 
  Value = "value", 
  NodeID = "name",
  NodeGroup = "foo",
  LinkGroup = "owner",
  colourScale = JS("d3.scaleOrdinal()
                   .domain(['James', 'Drew', 'Shep', 'Matt', 'Milf', 'Toby', 'R', 'Points'])
                   .range(['#bcbd22', '#17becf', '#ffb300', '#7f7f7f', '#d62728','#393b79', '#000', '#777']);"),
  fontSize = 11, 
  fontFamily = "Roboto",
  nodeWidth = 15,
  margin = list(right = 0)
)

sn <- onRender(
  sn,
  '
  function(el, x){
  var node_text = d3.select(el)
  .selectAll(".node text")
  .style("font-weight", "bold")
  .filter(function(d) { return (d.name.search("beats|scores") > -1); })
  .attr("x", x.options.nodeWidth - 20)
  .attr("text-anchor", "end");
  }
  '
)

# saveWidget(sn, "playoff_paths.html")

```

```{r, fig.height=7, results='asis'}
sn
```

Row 
-----------------------------------------------------------------------

### **Scenarios Spelled Out**

```{r}
scenarios_df <- links %>% 
  left_join(nodes, by = c("source" = "node")) %>% 
  select(-source, -target, -value, -foo) %>% 
  filter(stringr::str_length(scenario) > 0) %>%
  group_by(owner, scenario) %>% 
  summarise(outcomes = stringr::str_c(unique(name), collapse = "</br>")) %>% 
  rename(Owner = owner, Path = scenario, Steps = outcomes)

scenarios_df %>% 
  datatable(escape = FALSE, rownames = FALSE, height = 2800,
            options=list(
              scrollY = TRUE,
              ordering = FALSE,
              pageLength = 10,
              dom = 'tp',
              initComplete = JS("
                                function(settings, json) {
                                  $(this.api().table().body()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '11px'
                                  });
                                  $(this.api().table().header()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                  $(this.api().table().container()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                }
                                ")
            )
  )
```

LPP Scenarios
=====================================  

Row 
-----------------------------------------------------------------------

### **First Steps Towards 26.2 Miles**

```{r include=FALSE, message=FALSE, warning=FALSE}
links2 = tribble(
  ~source, ~target, ~value, ~owner, ~scenario,
  4, 20, 0.2, "Billy", "B1",
  9, 20, 0.2, "Billy", "B1",
  4, 21, 0.2, "Billy", "B2",
  3, 21, 0.2, "Billy", "B2",
  5, 22, 0.2, "Billy", "B3",
  3, 22, 0.2, "Billy", "B3",
  9, 22, 0.2, "Billy", "B3",
  10, 22, 0.2, "Billy", "B3",
  7, 22, 0.2, "Billy", "B3",
  5, 23, 0.2, "Billy", "B4",
  3, 23, 0.2, "Billy", "B4",
  9, 23, 0.2, "Billy", "B4",
  12, 23, 0.2, "Billy", "B4",
  0, 23, 0.2, "Billy", "B4",
  5, 24, 0.2, "Billy", "B5",
  3, 24, 0.2, "Billy", "B5",
  9, 24, 0.2, "Billy", "B5",
  10, 24, 0.2, "Billy", "B5",
  12, 24, 0.2, "Billy", "B5",
  2, 25, 0.2, "Keith", "K1",
  8, 25, 0.2, "Keith", "K1",
  2, 26, 0.2, "Keith", "K2",
  5, 26, 0.2, "Keith", "K2",
  3, 27, 0.2, "Keith", "K3",
  5, 27, 0.2, "Keith", "K3",
  8, 27, 0.2, "Keith", "K3",
  14, 27, 0.2, "Keith", "K3",
  7, 27, 0.2, "Keith", "K3",
  3, 28, 0.2, "Keith", "K4",
  5, 28, 0.2, "Keith", "K4",
  8, 28, 0.2, "Keith", "K4",
  16, 28, 0.2, "Keith", "K4",
  1, 28, 0.2, "Keith", "K4",
  3, 29, 0.2, "Keith", "K5",
  5, 29, 0.2, "Keith", "K5",
  8, 29, 0.2, "Keith", "K5",
  14, 29, 0.2, "Keith", "K5",
  16, 29, 0.2, "Keith", "K5",
  0, 30, 0.2, "Tony", "T1",
  5, 30, 0.2, "Tony", "T1",
  11, 30, 0.2, "Tony", "T1",
  3, 30, 0.2, "Tony", "T1",
  15, 30, 0.2, "Tony", "T1",
  7, 30, 0.2, "Tony", "T1",
  0, 31, 0.2, "Tony", "T2",
  5, 31, 0.2, "Tony", "T2",
  11, 31, 0.2, "Tony", "T2",
  3, 31, 0.2, "Tony", "T2",
  15, 31, 0.2, "Tony", "T2",
  19, 31, 0.2, "Tony", "T2",
  6, 32, 0.2, "Ross", "R1",
  5, 32, 0.2, "Ross", "R1",
  13, 32, 0.2, "Ross", "R1",
  3, 32, 0.2, "Ross", "R1",
  17, 32, 0.2, "Ross", "R1",
  1, 32, 0.2, "Ross", "R1",
  6, 33, 0.2, "Ross", "R2",
  5, 33, 0.2, "Ross", "R2",
  13, 33, 0.2, "Ross", "R2",
  3, 33, 0.2, "Ross", "R2",
  17, 33, 0.2, "Ross", "R2",
  18, 33, 0.2, "Ross", "R2",
  20, 34, 0.4, "Billy", "",
  21, 34, 0.4, "Billy", "",
  22, 34, 1, "Billy", "",
  23, 34, 1, "Billy", "",
  24, 34, 1, "Billy", "",
  25, 35, 0.4, "Keith", "",
  26, 35, 0.4, "Keith", "",
  27, 35, 1, "Keith", "",
  28, 35, 1, "Keith", "",
  29, 35, 1, "Keith", "",
  30, 36, 1.2, "Tony", "",
  31, 36, 1.2, "Tony", "",
  32, 37, 1.2, "Ross", "",
  33, 37, 1.2, "Ross", ""

)

nodes2 = tribble(
  ~node, ~name, ~foo,
  0, "James beats Tony", "R",
  1, "Tony beats James", "R",
  2, "Kevin beats Keith", "R",
  3, "Keith beats Kevin", "R",
  4, "Matt beats Billy", "R",
  5, "Billy beats Matt", "R",
  6, "Milf beats Ross", "R",
  7, "Ross beats Milf", "R",
  8, "Billy scores > Keith + 33.4", "Points",
  9, "Billy scores < Keith + 33.4", "Points",
  10, "Tony scores > Billy + 2.6", "Points",
  11, "Tony scores < Billy + 2.6", "Points",
  12, "Ross scores > Billy + 4.8", "Points",
  13, "Ross scores < Billy + 4.8", "Points",
  14, "Tony scores > Keith + 36", "Points",
  15, "Tony scores < Keith + 36", "Points",
  16, "Ross scores > Keith + 28.6", "Points",
  17, "Ross scores < Keith + 28.6", "Points",
  18, "Tony scores > Ross + 7.4", "Points",
  19, "Tony scores < Ross + 7.4", "Points",
  20, "B1", "Billy",
  21, "B2", "Billy",
  22, "B3", "Billy",
  23, "B4", "Billy",
  24, "B5", "Billy",
  25, "K1", "Keith",
  26, "K2", "Keith",
  27, "K3", "Keith",
  28, "K4", "Keith",
  29, "K5", "Keith",
  30, "T1", "Tony",
  31, "T2", "Tony",
  32, "R1", "Ross",
  33, "R2", "Ross",
  34, "Billy MARATHON", "Billy",
  35, "Keith MARATHON", "Keith",
  36, "Tony MARATHON", "Tony",
  37, "Ross MARATHON", "Ross"
)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
sn2 <- sankeyNetwork(
  Links = links2,
  Nodes = nodes2, 
  Source = "source",
  Target = "target", 
  Value = "value", 
  NodeID = "name",
  NodeGroup = "foo",
  LinkGroup = "owner",
  colourScale = JS("d3.scaleOrdinal()
                   .domain(['Billy', 'Keith', 'Tony', 'Ross', 'R', 'Points'])
                   .range(['#bcbd22', '#17becf', '#ffb300', '#7f7f7f', '#000', '#777']);"),
  fontSize = 11, 
  fontFamily = "Roboto",
  nodeWidth = 15,
  margin = list(right = 0)
)

sn2 <- onRender(
  sn2,
  '
  function(el, x){
  var node_text2 = d3.select(el)
  .selectAll(".node text")
  .style("font-weight", "bold")
  .filter(function(d) { return (d.name.search("beats|scores") > -1); })
  .attr("x", x.options.nodeWidth - 20)
  .attr("text-anchor", "end");
  }
  '
)
```

```{r, fig.height=6}
sn2
```

Row 
-----------------------------------------------------------------------

### **Scenarios Spelled Out**

```{r}
scenarios_df2 <- links2 %>% 
  left_join(nodes2, by = c("source" = "node")) %>% 
  select(-source, -target, -value, -foo) %>% 
  filter(stringr::str_length(scenario) > 0) %>%
  group_by(owner, scenario) %>% 
  summarise(outcomes = stringr::str_c(unique(name), collapse = "</br>")) %>% 
  rename(Owner = owner, Path = scenario, Steps = outcomes)

scenarios_df2 %>% 
  datatable(escape = FALSE, rownames = FALSE, height = 2800,
            options=list(
              scrollY = TRUE,
              ordering = FALSE,
              pageLength = 10,
              dom = 'tp',
              initComplete = JS("
                                function(settings, json) {
                                  $(this.api().table().body()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '11px'
                                  });
                                  $(this.api().table().header()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                  $(this.api().table().container()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                }
                                ")
            )
  )
```

Power Rankings
=====================================  

Row 
-----------------------------------------------------------------------

### **Rankings & Stats**

```{r}
pr_week12 <- get_powerrankings(2017, 12, data_dir = "../data")
```

```{r}
pr_week12 %>% 
  arrange(`POWER                             RANK                           SCORE`) %>% 
  select(-Δ, -CONS, -`POWER                             RANK                           SCORE`) %>% 
  rename(`Playoff Prob.` = `PO Odds`, Team = `TEAM NAME`, 
         `Power Rank` = `POWER RANK`, Record = RECORD, 
         `Overall Record` = `OVERALL WINS`, 
         `Roster Strengh` = `R.O.S. ROSTER`) %>% 
  mutate(`Playoff Prob.` = glue::glue("{prob}%", 
                                      prob = `Playoff Prob.` * 100),
         PPG = map_chr(PPG, function(x) {str_split(x, ",") %>% 
             flatten_chr() %>% 
             rev() %>% 
             str_c(collapse = " (") %>% 
             str_c(")")
           }),
         PPG = str_replace(PPG, "ppg", "")) %>% 
  datatable(escape = FALSE, rownames = FALSE,
            options=list(
              scrollY = TRUE,
              ordering = FALSE,
              pageLength = 12,
              dom = 't',
              initComplete = JS("
                                function(settings, json) {
                                  $(this.api().table().body()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '11px'
                                  });
                                  $(this.api().table().header()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                  $(this.api().table().container()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                }
                                ")
            )
  ) %>% 
  formatStyle(c("Team", "Power Rank", "Record", "Overall Record"), textAlign = "center")
```

Row 
-----------------------------------------------------------------------

### Column Key

```{r}
tribble(
  ~Column, ~Description,
  "Team", 'Best attempt to get everyone\'s team name correct. Stop changing your team names, assholes.',
  "Power Rank", 'Current power rank, calculated based on <b><a href="https://www.reddit.com/r/fantasyfootball/comments/6y08cr/gators_2017_ff_power_ranking_spreadsheet_for_use/" target="_blank">this spreadsheet</a></b> I found on reddit.',
  "Playoff Prob.",  '("Prob." is short for "Probability") This is not used in any kind of determination of Power Rankings, but is copied from <a href="https://www.fantasypros.com/" target="_blank">FantasyPros</a> and displayed for shits and giggles. From the author: "*I currently use FPros for this, but am not super happy with it. They incorporate roster strength into it, which I don\'t want. FPros also does not take league setup like divisions and wildcards into account. I want just a straight up probability without anything subjective. if someone knows of a service that offers that, please let me know! But for now, I\'ll continue to use what I\'ve got.',
  "Record", 'Pretty self explanatory. You can find out more about how everything gets weighted at the link above.',
  "Overall Record", 'This is what your record would be if you played every team every week (basically, how your score stacks up against everyone else).',
  "PPG", 'Points scored per game (and corresponding league rank in that category).',
  "Roster Strength", 'Rest-of-season roster strength, relative to the rest of the league. This is also copied from FantasyPros.'
) %>% 
  datatable(escape = FALSE, rownames = FALSE, height = 2800,
            options=list(
              scrollY = TRUE,
              ordering = FALSE,
              pageLength = 12,
              dom = 't',
              initComplete = JS("
                                function(settings, json) {
                                  $(this.api().table().body()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '11px'
                                  });
                                  $(this.api().table().header()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                  $(this.api().table().container()).css({
                                    'font-family': 'Roboto, Open Sans, sans-serif',
                                    'font-size': '12px'
                                  });
                                }
                                ")
            )
  )
```


Trends
=====================================  

Row
-----------------------------------------------------------------------

### **Power Rank Trends**

```{r}
trends_df <- read_trends(2017) %>% 
  mutate(week = forcats::fct_inorder(week))

current_order <- trends_df %>% 
  filter(week == "WEEK 12", trend_type == "power_rank") %>% 
  arrange(rank) %>% 
  .[["Team"]]
```

```{r, fig.height=5}
p <- trends_df %>% 
  filter(trend_type == "power_rank",
         !is.na(rank)) %>% 
  mutate(Team = factor(Team, levels = current_order),
         ttip = glue::glue("<b>{team}</b>\n{week} rank: <b>{rank}</b>",
                            team = Team, rank = rank, week = str_to_title(week))) %>% 
  ggplot2::ggplot(aes(x = as.numeric(week), y = rank)) +
  geom_line(aes(colour = Team)) +
  geom_point(aes(colour = Team, text = ttip)) +
  scale_color_calc() +
  scale_x_continuous(breaks = 1:13,
                     labels = levels(trends_df$week)[1:13],
                     limits = c(1, 13)) +
  scale_y_reverse(breaks = 1:13) +
  ylab("Power Rank") +
  xlab("") +
  guides(colour = FALSE) +
  custom_theme_bw() +
  theme(axis.text.x = element_text(angle = -30, hjust = 0))
# p
ggplotly(p, tooltip = "text") %>% 
  layout(margin = list(b = 55))
```


